#!/bin/bash
# 
# **ENVIRONMENTAL PACKAGES SHOULD REMAIN STATIC FOR A GIVEN MODEL EXPERIMENT**
# 
# This shell script loads the necessary environmental packages and sets
# environmental variables/paths that WRF looks for during compile and
# when running.
# 
# Setup using modules on OSCER.
# 

module purge
module load netCDF-Fortran/4.5.3-iimpi-2021a
module load JasPer/2.0.33-GCCcore-11.3.0
module load libpng/1.6.37-GCCcore-11.3.0

export I_MPI_CC=icc
export I_MPI_CXX=icpc
export I_MPI_F90=ifort
export I_MPI_F77=ifort
export I_MPI_FC=ifort

# Necessary if remotely working from a Mac
export LC_ALL="en_US.UTF-8"

#FOR WRF

#WRF
export WRF_EM_CORE=1
export WRFIO_NCD_LARGE_FILE_SUPPORT=1

#NETCDF
export LCLSRC=$HOME/localsrc
export NETCDF=$LCLSRC/netcdf
export NETCDF_INC=$NETCDF/include
export NETCDF_LIB=$NETCDF/lib
export NETCDF_BIN=$NETCDF/bin
# Copy over NETCDF files to common directory since netcdf C and FORTRAN modules are separate
rm -rf $LCLSRC
mkdir -p $LCLSRC
mkdir -p $NETCDF
mkdir $NETCDF/include
mkdir $NETCDF/lib
mkdir $NETCDF/bin
cp -raf $EBROOTNETCDF/include/*  $NETCDF/include
cp -raf $EBROOTNETCDF/lib64/* $NETCDF/lib
cp -raf $EBROOTNETCDF/bin/* $NETCDF/bin
cp -raf $EBROOTNETCDFMINFORTRAN/include/* $NETCDF/include
cp -raf $EBROOTNETCDFMINFORTRAN/lib/* $NETCDF/lib
cp -raf $EBROOTNETCDFMINFORTRAN/bin/* $NETCDF/bin

#HDF5
export HDF5=$EBROOTHDF5

# FOR WPS

#jasper
export JASPER=$EBROOTJASPER
export JASPERLIB=$JASPER/lib
export JASPERINC=$JASPER/include

#libpng
export LIBPNG=$EBROOTLIBPNG
export LIBPNGLIB=$LIBPNG/lib
export LIBPNGINC=$LIBPNG/include

